### ISSUE TITLE
Add notifications per user

### ISSUE THREAD

**Issue by petersmithca** [petersmithca/humhub-api#33]
Add a route to get notifications for a specific user.

**Comment by petersmithca** [comment]
@censtudios - this should add the enhancement you were looking for

**Comment by Censtudios** [comment]
Looking good. Will update the module on my site later today.

Thanks a lot

**Comment by Censtudios** [comment]
I uploaded the new files and tried it (/api/notification/752/?access_token=xxx) and I get a "page not found". The notifications for all users worked though.

I will take a look again later when I have more time. Maybe I did something wrong.

**Comment by petersmithca** [comment]
Maybe try without that last /

**Comment by Censtudios** [comment]
I tried with and without

**Comment by petersmithca** [comment]
hmm odd, was working for me locally.  I did have to restart nginx tho for
whatever reason. maybe try restarting your webserver? Will have a look
again when home as well.

**Comment by Censtudios** [comment]
I disabled the module and re-enabled it. It works now xD So that was the issue.

And it's indeed without the last /

**Comment by petersmithca** [comment]
ah ok, it must cache the config I guess!  Thanks for the update
