### ISSUE TITLE
return lists for given users

### ISSUE THREAD

**Issue by frey1esm** [petersmithca/humhub-api#36]
Currently a call to /api/space returns all spaces. The api would be more useful if you could add a user id:

For example,
`/api/user/1/space` would return all spaces for user_id=1

Same for posts, comments, etc. 

In addition,

`api/space/1/user` could return all users that belong to space_id=1.

X2CRM has a robust Yii2 [API implementation](http://wiki.x2crm.com/wiki/REST_API_Reference).

**Comment by petersmithca** [comment]
Hi there

Thank you for your input, however I am no longer able to support this module.  If you would like to be added as an author, or want to fork the project please feel free, or let me know.
