### ISSUE TITLE
File upload API

### ISSUE THREAD

**Issue by chavika86** [petersmithca/humhub-api#39]
Is it possible to Create post with multiple file upload

**Comment by petersmithca** [comment]
I'm sorry, I never implemented anything like this.

**Comment by chavika86** [comment]
How about just file upload

**Comment by petersmithca** [comment]
Again not something I've implemented.  I'm sure someone could extend the
api, not something I currently have much time for.

**Comment by chavika86** [comment]
Thank you peter
