### ISSUE TITLE
Setting unknown property

### ISSUE THREAD

**Issue by bolico** [petersmithca/humhub-api#41]
Good morning, when entering json data, I get this log, you have how to help?

{
  "name": "Unknown Property",
  "message": "Setting unknown property: humhub\\modules\\content\\models\\Content::user_id",
  "code": 0,
  "type": "yii\\base\\UnknownPropertyException",
  "file": "C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\base\\Component.php",
  "line": 197,
  "stack-trace": [
    "#0 C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(272): yii\\base\\Component->__set('user_id', 1)",
    "#1 C:\\xampp\\htdocs\\divulga\\protected\\humhub\\modules\\api\\controllers\\PostController.php(133): yii\\db\\BaseActiveRecord->__set('user_id', 1)",
    "#2 [internal function]: humhub\\modules\\api\\controllers\\PostController->actionCreate()",
    "#3 C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(55): call_user_func_array(Array, Array)",
    "#4 C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\base\\Controller.php(154): yii\\base\\InlineAction->runWithParams(Array)",
    "#5 C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\base\\Module.php(454): yii\\base\\Controller->runAction('create', Array)",
    "#6 C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\web\\Application.php(87): yii\\base\\Module->runAction('api/post/create', Array)",
    "#7 C:\\xampp\\htdocs\\divulga\\protected\\vendor\\yiisoft\\yii2\\base\\Application.php(375): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
    "#8 C:\\xampp\\htdocs\\divulga\\index.php(25): yii\\base\\Application->run()",
    "#9 {main}"
  ]
}

**Comment by bolico** [comment]
Sorted out
Line 133
$ Post-> content-> created_by = $ user_id;
Api / controllers / PostController.php

**Comment by petersmithca** [comment]
Sorry, I have not tested this against any newer versions, nor do I have time to support it anymore at present.

**Comment by bolico** [comment]
Tks
