### ISSUE TITLE
PHP Fatal Error on /api/user/login/:username/:password?access_token=XXXXXXXX

### ISSUE THREAD

**Issue by onusgit** [petersmithca/humhub-api#42]
Hello 

I am using login api, when i call this api, i get 

<response>
<name>PHP Fatal Error</name>
<message>
Class 'humhub\modules\user\models\forms\AccountLogin' not found
</message>
<code>1</code>
<type>yii\base\ErrorException</type>
<file>
/home/abc/abc.com/community/protected/modules/api/controllers/UserController.php
</file>
<line>51</line>
<stack-trace>
<item>
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
</item>
<item>#1 {main}</item>
</stack-trace>
</response>

I am new in yii, i try some solution but not success.

can you help to fix this issue?

thanks

**Comment by petersmithca** [comment]
Hi there

Thank you for your input, however I am no longer able to support this module.  If you would like to be added as an author, or want to fork the project please feel free, or let me know.
