### ISSUE TITLE
undefined field user_id in POST to /api/post

### ISSUE THREAD

**Issue by Lercher** [petersmithca/humhub-api#43]
At https://github.com/petersmithca/humhub-api/blob/master/controllers/PostController.php#L133 in actionCreate() I suggest

    $post->content->created_by = $user_id;

instead of ...->user_id = ... which is not defined in my edition of humhub.

see: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/models/Content.php#L31

Thanks, Martin

**Comment by petersmithca** [comment]
Hi there

Thank you for your input, however I am no longer able to support this module.  If you would like to be added as an author, or want to fork the project please feel free, or let me know.
