### ISSUE TITLE
Adding an integrated REST Client

### ISSUE THREAD

**Issue by zikwall** [petersmithca/humhub-api#45]
You can think of embedding the client's REST in the API module, using the example of this module:
[Yii2 REST Client](https://github.com/zhuravljov/yii2-rest "api client")

And add it as a child module:
```

'id' => 'api',
    'class' => 'humhub\modules\api\Module',
    'namespace' => 'humhub\modules\api',
    'controllerNamespace' => 'humhub\modules\api',
	'bootstrap' => ['rest'],
	'modules' => [
		'rest' => [
			'class' => 'humhub\modules\api\modules\rest\Module',
			'name' => 'My Rest Client',
			'baseUrl' => 'http://localhost/api/api',
		],
	],

```

and go to URL: site.net/api/rest

#### UPD:
**There was a misunderstanding, the module is no longer supported, it's a pity ...**

**Comment by petersmithca** [comment]
Sorry, I no longer have the time to work on/support this module. Feel free to fork it.
